site_name: AOE3 AI Scripting Guide
site_url: https://aoe3mc.github.io/ai-guide/
site_author: Thinot Mandresy
site_description: A guide to AI scripting in Age of Empires III.

repo_name: aoe3mc/ai-guide
repo_url: https://github.com/aoe3mc/ai-guide

copyright: Copyright &copy; 2023 <a href="http://github.com/thinotmandresy" target="_blank" rel="noopener noreferrer">Thinot Mandresy</a>

theme:
  name: material
  language: en
  features:
    - content.code.annotate
    - content.code.copy
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  palette:
    - scheme: default
      primary: black
      accent: teal
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: yellow
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: img/favicon.png
  icon:
    annotation: material/plus-circle
    logo: material/book-open-page-variant

plugins:
  - search

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/aoe3mc
    - icon: fontawesome/brands/discord
      link: https://discord.gg/7zRgTaPrrv

markdown_extensions:
  - abbr
  - attr_list
  - admonition
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      use_pygments: true
      linenums: true
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.snippets:
      auto_append:
        - includes/tooltips.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true

nav:
    - Introduction:
        - index.md
        - Getting Started: getting-started.md
    
    - The XS Language:
        - xs/index.md
        - Comments: xs/comments.md
        - Variables: xs/variables.md
        - Operators: xs/operators.md
        - Strings: xs/strings.md
        - Conditionals: xs/conditionals.md
        - Loops: xs/loops.md
        - Labels: xs/labels.md
        - Functions: xs/functions.md
        - Rules: xs/rules.md
        - Includes: xs/includes.md
        - Variables Scope: xs/variables-scope.md
        - Vectors: xs/vectors.md
        - Arrays: xs/arrays.md
        - Good Practices: xs/good-practices.md
    
    - AI Scripting:
        - ai/index.md
        - Protounits: ai/protounits.md
    
    - Reference:
        - The XS Language:
            - Keywords: reference/keywords.md

        - Functions & Constants:
            - Constants:
                - Ages: reference/constants/ages.md
                - Area Group Types: reference/constants/area-group-types.md
                - Area Types: reference/constants/area-types.md
                - Attack Routes: reference/constants/attack-routes.md
                - Building Placement:
                    - Building Placement Events: reference/constants/building-placement/events.md
                    - Building Placement Preferences: reference/constants/building-placement/preferences.md
                - Card Types: reference/constants/card-types.md
                - Communication:
                    - Chat Verbs: reference/constants/communication/chat-verbs.md
                    - Response Types: reference/constants/communication/response-types.md
                    - Target Strategies: reference/constants/communication/target-strategies.md
                    - Target Types: reference/constants/communication/target-types.md
                - Default Escrows: reference/constants/default-escrows.md
                - Difficulties: reference/constants/difficulties.md
                - Events: reference/constants/events.md
                - Filename Constants: reference/constants/filename.md
                - Game Constants:
                    - reference/constants/game.md
                    - Game Modes: reference/constants/game-modes.md
                    - Game Types: reference/constants/game-types.md
                - Micromanagement: reference/constants/micromanagement.md
                - Movement Types: reference/constants/movement-types.md
                - Nugget Types: reference/constants/nugget-types.md
                - Opportunities:
                    - Opportunity Sources: reference/constants/opportunities/opportunity-sources.md
                    - Opportunity Types: reference/constants/opportunities/opportunity-types.md
                    - Opportunity Target Types: reference/constants/opportunities/opportunity-target-types.md
                - Plans:
                    - Plan Types:
                        - reference/constants/plans/plan-types.md
                        - Attack Strategy Plans:
                            - reference/constants/plans/attack-strategy-plans/index.md
                        - Attack Plans:
                            - reference/constants/plans/attack-plans/index.md
                            - Attack Route Patterns: reference/constants/plans/attack-plans/attack-route-patterns.md
                            - Base Attack Mode: reference/constants/plans/attack-plans/base-attack-mode.md
                            - Retreat Mode: reference/constants/plans/attack-plans/retreat-modes.md
                        - Build Plans:
                            - reference/constants/plans/build-plans/index.md
                            - Build Plan Influence Falloff: reference/constants/plans/build-plans/bpi-falloff.md
                        - Build Wall Plans:
                            - reference/constants/plans/build-wall-plans/index.md
                            - Wall Types: reference/constants/plans/build-wall-plans/wall-types.md
                        - Combat Plans:
                            - reference/constants/plans/combat-plans/index.md
                            - Attack Route Patterns: reference/constants/plans/combat-plans/attack-route-patterns.md
                            - Combat Types: reference/constants/plans/combat-plans/combat-types.md
                            - Done Modes: reference/constants/plans/combat-plans/done-modes.md
                            - Retreat Modes: reference/constants/plans/combat-plans/retreat-modes.md
                            - Target Modes: reference/constants/plans/combat-plans/target-modes.md
                        - Defend Plans:
                            - reference/constants/plans/defend-plans/index.md
                        - Explore Plans:
                            - reference/constants/plans/explore-plans/index.md
                        - Fish Plans:
                            - reference/constants/plans/fish-plans/index.md
                        - Gather Goal Plans:
                            - reference/constants/plans/gather-goal-plans/index.md
                        - Gather Plans:
                            - reference/constants/plans/gather-plans/index.md
                        - Goal Plans:
                            - reference/constants/plans/goal-plans/index.md
                            - Goal Types: reference/constants/plans/goal-plans/goal-types.md
                            - Goal SubTypes: reference/constants/plans/goal-plans/goal-subtypes.md
                            - Target Types: reference/constants/plans/goal-plans/target-types.md
                        - Herd Plans:
                            - reference/constants/plans/herd-plans/index.md
                        - Mission Plans:
                            - reference/constants/plans/mission-plans/index.md
                            - Mission Types: reference/constants/plans/mission-plans/mission-types.md
                        - Native Research Plans (a.k.a. Dance Plans):
                            - reference/constants/plans/native-research-plans/index.md
                        - Nugget Plans:
                            - reference/constants/plans/nugget-plans/index.md
                        - Progression Plans:
                            - reference/constants/plans/progression-plans/index.md
                        - Repari Plans:
                            - reference/constants/plans/repair-plans/index.md
                        - Research Plans:
                            - reference/constants/plans/research-plans/index.md
                        - Reserve Plans:
                            - reference/constants/plans/reserve-plans/index.md
                        - Tower Plans:
                            - reference/constants/plans/tower-plans/index.md
                        - Trade Plans:
                            - reference/constants/plans/trade-plans/index.md
                        - Train Plans:
                            - reference/constants/plans/train-plans/index.md
                        - Transport Plans:
                            - reference/constants/plans/transport-plans/index.md
                            - Path Types: reference/constants/plans/transport-plans/path-types.md
                    - Plan States: reference/constants/plans/plan-states.md
                    - Plan Events: reference/constants/plans/plan-events.md
                - Player Constants:
                    - reference/constants/player.md
                    - Player Relations: reference/constants/player-relations.md
                - Resign Types: reference/constants/resign-types.md
                - Resource Gathering:
                    - Resource Gathering Systems: reference/constants/resource-gathering/rgp.md
                    - Resource SubTypes: reference/constants/resource-gathering/resource-subtypes.md
                    - Gatherer Limit: reference/constants/resource-gathering/gatherer-limit.md
                    - TargetSelect Factor Constants: reference/constants/resource-gathering/ts-factor.md
                - Resource Types: reference/constants/resource-types.md
                - Starting Resources: reference/constants/starting-resources.md
                - Techs:
                    - Tech Statuses: reference/constants/techs/tech-statuses.md
                - Trading Post Sockets:
                    - Socket States: reference/constants/sockets/socket-states.md
                    - Socket Types: reference/constants/sockets/socket-types.md
                - Units:
                    - Abstract Unit Types: reference/constants/units/abstract-unit-types.md
                    - Unit States: reference/constants/units/unit-states.md
                - Vector Constants: reference/constants/vector.md
            
            - Functions:
                - XS Functions: reference/functions/xs.md
                - KB Functions: reference/functions/kb.md
                - AI Functions: reference/functions/ai.md
